/* global require */
const { contextBridge, ipcRenderer } = require("electron")

contextBridge.exposeInMainWorld("api", {
  addProduct: (product) => ipcRenderer.invoke("add-product", product),
  getAllProducts: () => ipcRenderer.invoke("get-all-products"),
  getProductById: (id) => ipcRenderer.invoke("get-product-by-id", id),
  updateProduct: (id, product) => ipcRenderer.invoke("update-product", { id, product }),
  deleteProduct: (id) => ipcRenderer.invoke("delete-product", id),
  inactivateProduct: (id) => ipcRenderer.invoke("inactivate-product", id),
  addProductStock: (id, quantity) => ipcRenderer.invoke("add-product-stock", { id, quantity }),
  getAllCategories: () => ipcRenderer.invoke("get-all-categories"),
  getCategoriesWithProductCounts: () => ipcRenderer.invoke("get-categories-with-product-counts"),
  addCategory: (category) => ipcRenderer.invoke("add-category", category),
  updateCategory: (id, category) => ipcRenderer.invoke("update-category", { id, category }),
  deactivateCategory: (id) => ipcRenderer.invoke("deactivate-category", id),
  reactivateCategory: (id) => ipcRenderer.invoke("reactivate-category", id),
  getAllUnits: () => ipcRenderer.invoke("get-all-units"),
  getUnitsWithProductCounts: () => ipcRenderer.invoke("get-units-with-product-counts"),
  addUnit: (unit) => ipcRenderer.invoke("add-unit", unit),
  updateUnit: (id, unit) => ipcRenderer.invoke("update-unit", { id, unit }),
  deactivateUnit: (id) => ipcRenderer.invoke("deactivate-unit", id),

  addProductCategory: (productId, categoryId) => ipcRenderer.invoke("add-product-category", productId, categoryId),
  getProductCategoriesByProductId: (productId) => ipcRenderer.invoke("get-product-categories-by-product-id", productId),
  removeProductCategory: (productId, categoryId) => ipcRenderer.invoke("remove-product-category", productId, categoryId),
  getBarcodesByProductId: (productId) => ipcRenderer.invoke("get-barcodes-by-product-id", productId),
  getAssignableUnitsByProductId: (productId) => ipcRenderer.invoke("get-assignable-units-by-product-id", productId),
  addBarcode: (barcodeData) => ipcRenderer.invoke("add-barcode", barcodeData),
  updateBarcode: (id, barcode) => ipcRenderer.invoke("update-barcode", { id, barcode }),
  deleteBarcode: (id) => ipcRenderer.invoke("delete-barcode", id),
  generateBarcode: () => ipcRenderer.invoke("generate-barcode"),

  createBill: (payload) => ipcRenderer.invoke("create-bill", payload),
  getBillById: (id) => ipcRenderer.invoke("get-bill-by-id", id),
  getOpenBills: () => ipcRenderer.invoke("get-open-bills"),
  getAllBills: () => ipcRenderer.invoke("get-all-bills"),
  saveBill: (payload) => ipcRenderer.invoke("save-bill", payload),
  resolveBarcode: (barcode) => ipcRenderer.invoke("resolve-barcode", barcode),
  cancelBill: (billId) => ipcRenderer.invoke("cancel-bill", billId),
  deleteBill: (billId) => ipcRenderer.invoke("delete-bill", billId),
  deleteAllBills: () => ipcRenderer.invoke("delete-all-bills"),
  getBillPayments: (billId) => ipcRenderer.invoke("get-bill-payments", billId),

  getSettings: () => ipcRenderer.invoke("get-settings"),
  getLogoDataUrl: () => ipcRenderer.invoke("get-logo-data-url"),
  updateSettings: (payload) => ipcRenderer.invoke("update-settings", payload),
  selectLogoFile: () => ipcRenderer.invoke("select-logo-file"),
  uploadLogo: (filePath) => ipcRenderer.invoke("upload-logo", filePath),

  login: (credentials) => ipcRenderer.invoke("auth-login", credentials),
  logout: () => ipcRenderer.invoke("auth-logout"),
  getSession: () => ipcRenderer.invoke("auth-session"),
  getAuthStatus: () => ipcRenderer.invoke("auth-status"),
  resetPassword: (payload) => ipcRenderer.invoke("auth-reset-password", payload),
  listUsers: () => ipcRenderer.invoke("auth-users"),
  createUser: (payload) => ipcRenderer.invoke("auth-create-user", payload),
  changeOwnPassword: (payload) => ipcRenderer.invoke("auth-change-own-password", payload),
})
